#!/bin/bash
#SBATCH -J tophat #A single job name for the array
#SBATCH -o stdout.d/tophat_%A_%a.out #Standard output
#SBATCH -e stderr.d/tophat_%A_%a.err #Standard error
#SBATCH -p serial_requeue#Partition
#SBATCH -t 120 #Running time of 2 hours
#SBATCH --mem-per-cpu 4000 #Memory request
#SBATCH -n 4 #Number of cores
#SBATCH -N 1 #All cores on one machine


R CMD BATCH GB_Sim_Analysis.R gbpendiff10_analysis.Rout
