#!/bin/bash
#SBATCH -J tophat #A single job name for the array
#SBATCH -o stdout.d/tophat_%A_%a.out #Standard output
#SBATCH -e stderr.d/tophat_%A_%a.err #Standard error
#SBATCH -p serial_requeue#Partition
#SBATCH -t 240 #Running time of 4 hours
#SBATCH --mem-per-cpu 2000 #Memory request
#SBATCH -n 4 #Number of cores
#SBATCH -N 1 #All cores on one machine


R CMD BATCH GradientBoostingSimulation_lp.R gbsimlp_${SLURM_ARRAY_TASK_ID}.Rout
